### ISSUE TITLE
Linux aarch64

### ISSUE THREAD

**Issue by DarrenN** [Bogdanp/racket-libsqlite3#3]
If I wanted to use this for Ubuntu on ARM64 would I essentially copy and rename the shell file https://github.com/Bogdanp/racket-libsqlite3/blob/master/bin/build-linux-x86-64.sh#L33 and change the name of the output artifact?

**Comment by Bogdanp** [comment]
I went ahead and added a package for `aarch64-linux` in f9f6b3a22f437b44b6d890c99d3f8f396dc0bd80 . I have a Pinebook lying around so I used that to build and publish [the package](https://pkgd.racket-lang.org/pkgn/package/libsqlite3-aarch64-linux).  As soon as the package server gets a chance to update its catalog, you should be able to install that package. Let me know if you run into any problems!

**Comment by DarrenN** [comment]
Amazing, thank you much! Waiting on the package server to do it's thing.

**Comment by DarrenN** [comment]
Updated the package from the server and `libsqlite3.so` is now included in the `lib` folder on a distribution. Thanks again!
